#. ~/bin/dotfiles/bash/git-completion.bash
#. ~/bin/dotfiles/bash/env
#. ~/bin/dotfiles/bash/config
#. ~/bin/dotfiles/bash/aliases 

. ~/lib/dotfiles/bash/git-completion.bash
. ~/lib/dotfiles/bash/env
. ~/lib/dotfiles/bash/config
. ~/lib/dotfiles/bash/aliases

# RVM is a great tool - load it always
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
